#!/bin/bash

for file in $(curl -k -s https://ds1.geodata.hawaii.edu/d/d73d975a2c/ |
                  grep href |
                  sed 's/.*href="//' |
                  sed 's/".*//' |
                  grep '\?file_name=Shark[1-9].*')
do

  local_file=$(echo "$file" | grep -o 'Shark.*gz')
  wget -O $local_file --no-check-certificate https://ds1.geodata.hawaii.edu/$file
done

