#!/bin/bash

#script used to get pear to merge reads
#assumes a bunch of files in the current directory
#called *R1*.fastq.gz and *R2*.fastq.gz
for gfile in *R1*.fastq.gz
do 
  pear -f $gfile \
  -r ${gfile/R1/R2} \
  -o merged/${gfile/_R1.fq/} \
  -n 33 \
  -t 33 \
  -q 10 \
  -j 2 \
   -u 0 \
   -m 550 \
   -y 1g
   
done


