#!/bin/bash
die() { echo "$@" 1>&2 ; exit 1; }

inputdir=$1
outputdir=$2
[[ -d $1 ]] || die "Bad input dir"
[[ -d $2 ]] || die "Badoutput dir"

echo "merging files..."
#script used to get pear to merge reads
#assumes a bunch of files in the current directory
#called *R1*.fastq.gz and *R2*.fastq.gz
for fq in $inputdir/*_R1_*.fastq.gz
do 
  pear -f $fq \
    -r ${fq/R1/R2} \
    -o $outputdir/$(basename ${fq/_R1_/_merged_} .fastq.gz) \
    -n 33 \
    -t 33 \
    -q 10 \
    -j 20\
    -u 0 \
    -m 550 \
    -y 8g
done


