#!/usr/bin/env bash

# Very simple script to get the external tools needed for this pipeline

# trim galore is maintained in code repo, since we modify it
# vcftools_x.tar.gz

# Packages to grab
# PEAR https://github.com/xflouris/PEAR.git
# fastx-toolkit https://github.com/agordon/fastx_toolkit.git
# rainbow http://sourceforge.net/projects/bio-rainbow/files/latest/download?source=files rainbow_src.tar.gz
# vcftools http://sourceforge.net/projects/vcftools/files/latest/download?source=files vcftools_src.tar.gz
# zlib (needed to compile pear on my system, but probably not generally)
# FastQC http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.3.zip fastqc.zip

git clone https://github.com/xflouris/PEAR.git
git clone https://github.com/agordon/libgtextutils.git
git clone https://github.com/agordon/fastx_toolkit.git
git clone https://github.com/marcelm/cutadapt.git
curl -L http://downloads.sourceforge.net/project/bio-rainbow/rainbow_2.0.3.tar.gz > rainbow_src.tar.gz
#wget http://downloads.sourceforge.net/project/bio-rainbow/rainbow_2.0.3.tar.gz -O rainbow_src.tar.gz
if [[ -f rainbow_src.tar.gz ]]; then
  tar zxvf rainbow_src.tar.gz
  rm rainbow_src.tar.gz
fi
curl -L http://downloads.sourceforge.net/project/vcftools/vcftools_0.1.12b.tar.gz > vcftools_src.tar.gz
#wget http://sourceforge.net/projects/vcftools/files/latest/download?source=files -O vcftools_src.tar.gz
if [[ -f vcftools_src.tar.gz ]]; then
  tar zxvf vcftools_src.tar.gz
  rm vcftools_src.tar.gz
fi
wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.3.zip -O fastqc.zip
if [[ -f fastqc.zip ]]; then 
  unzip fastqc.zip
  rm fastqc.zip
fi
wget http://cython.org/release/Cython-0.22.tar.gz -O cython.tar.gz
if [[ -f cython.tar.gz ]]; then
  tar zxvf cython.tar.gz
  rm cython.tar.gz
fi
git clone https://github.com/dzerbino/velvet.git